 SETOPT  PARM(HOBSET=YES)
 SETOPT  PARM(RMODE=SPLIT)
<#if env["GERS_DB2_ASM"] == "Y">
 INCLUDE SYSLIB(GVBMRSQ)
</#if>
 INCLUDE SYSLIB(GVBMR95)
 INCLUDE SYSLIB(GVBMR96)
 ENTRY   GVBMR95
 ALIAS   GVBMR95E,GVBMR95R
 NAME    GVBMR95(R)
